name: ciclope
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - tifffile
  - matplotlib
  - meshio==5.0.0
  - scikit-image
  - pygalmesh==10.6.0
  - itkwidgets
  - itk
  - vtk
  - tqdm
  - numexpr
  - pypng
  - pip>=20.1
  - pip:
      - sphinx==4.2.0
      - sphinx_rtd_theme==1.0.0
      - myst-nb==0.16.0
      - ipykernel
      - PyMCubes
      - ccx2paraview
      - ciclope